#include <iostream>
#include <stdlib.h> 
#include <fstream>
#include <string.h>
#include <stdio.h>
#include <stack>
#include <vector>
#include <cstring>
#include <cstdlib>
#include <cerrno>
#include <dirent.h>
#include <sys/stat.h>
